version: "3.7"
services:
  web:
    image: https
    container_name: Apache
    depends_on:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./www:/var/www
  db:
    image: mysql
    container_name: mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
