version: "3.7"
services:
  web:
    image: httpd
    container_name: Apache
    depends_on:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"

